name: "github"
version: "0.0.10"
usage: ""
description: ""
ignoreFlags: false
downloaders:
- command: "./bin/repo.sh"
  protocols:
  - "github"
- command: "./bin/release.sh"
  protocols:
  - "github+release"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
