name: "github"
version: "1.1.3"
usage: ""
description: ""
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/bin/helm-github.sh"
downloaders:
- command: "./bin/repo.sh"
  protocols:
  - "github"
- command: "./bin/release.sh"
  protocols:
  - "github+release"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
