name: "github"
version: "0.3.5"
usage: "Chart repositories on Github Releases"
description: |-
  Manage repositories on Github Releases
command: "$HELM_PLUGIN_DIR/bin/helm-github"
downloaders:
- command: "scripts/pull.sh"
  protocols:
  - "github+release"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"