name: Build Proxy Chart
on: 
  push:
    tags:
      - 1.*

env:
  TAG: $(git describe --tags --abbrev=0)

jobs:
  build:
    name: Build NodeJS version
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: proxy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -f ./Dockerfile -t docker.pkg.github.com/web-seven/helm-github/helm-github-plugin-proxy:${{ env.TAG }} .
      - name: Login to Github Docker Registry
        run: docker login --username ${GITHUB_ACTOR} --password ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
      - name: Push Docker image to registry.
        run: docker push docker.pkg.github.com/web-seven/helm-github/helm-github-plugin-proxy:${{ env.TAG }}
      - name: Create Helm Chart
        working-directory: charts/helm-github-proxy
        run: |
          helm plugin install https://github.com/web-seven/helm-github.git
          helm repo add helm-github github://web-seven/helm-github
          helm package --version ${{ env.TAG }} --app-version ${{ env.TAG }} ./
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}"
          git tag -a helm-github-proxy-${{ env.TAG }} -m ''
          git push origin helm-github-proxy-${{ env.TAG }}
          helm github push helm-github-proxy-${{ env.TAG }}.tgz helm-github ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
      